### ISSUE TITLE
Invalid QR generate with code

### ISSUE THREAD

**Issue by iAmAndroidDeveloper** [duyquoc1508/napas-qr#1]
We try with same code but its showing invalid qr / QR not support when scan from app
our result is @duyquoc1508 

00020101021238530010A0000007270123000697041601092241234560208QRIBFTTA53037045405
100005802VN62340107NPS68690819TRANSFER TO SOMEONE6304C2E6

**Comment by duyquoc1508** [comment]
The problem is due to invalid beneficiary account `receiverNumber`. Because it's an example, I used a random account, leading to this error when scanning from the app. If you use a valid bank account everything works correctly.
Seem to my example has confused you. I will update them to a valid account. @iAmAndroidDeveloper

**Comment by iAmAndroidDeveloper** [comment]
@duyquoc1508 thanks for your valuable answer, got your point and already manage our side
But yes when we try with order id its cause issue
one more things i need to ask that, how i can verify generated QR is valid or not?
